export const STATUS_FAMILIES = {
  neutral: ["new", "draft"],
  active: ["created", "assigned", "in_progress", "ongoing", "under_review", "quotation_submitted", "client_discussion", "sent_to_client", "client_sent", "submitted", "qs_review", "converted_to_po", "partially_fulfilled", "issued"],
  warning: ["pending", "review", "qs_estimation_pending", "revision_requested", "ready", "pending_approval"],
  success: ["approved", "completed", "closed", "settled"],
  danger: ["rejected", "cancelled", "archived", "void"],
  hold: ["on_hold"],
} as const;

export type StatusFamily = keyof typeof STATUS_FAMILIES;

export const statusLabels: Record<string, string> = {
  new: "New",
  draft: "Draft",
  under_review: "Under Review",
  qs_estimation_pending: "QS Estimation Pending",
  quotation_submitted: "Quotation Submitted",
  client_discussion: "Client Discussion",
  in_progress: "In Progress",
  ongoing: "Ongoing",
  pending: "Pending",
  review: "Review",
  ready: "Ready",
  created: "Created",
  assigned: "Assigned",
  submitted: "Submitted",
  qs_review: "QS Review",
  converted_to_po: "Converted To PO",
  partially_fulfilled: "Partially Fulfilled",
  pending_approval: "Pending Approval",
  issued: "Issued",
  void: "Void",
  settled: "Settled",
  sent_to_client: "Sent to Client",
  client_sent: "Client Sent",
  revision_requested: "Revision Requested",
  approved: "Approved",
  completed: "Completed",
  rejected: "Rejected",
  archived: "Archived",
  cancelled: "Cancelled",
  closed: "Closed",
  on_hold: "On Hold",
};
